### ISSUE TITLE
Remove hardcoded values from PortScanner.py

### ISSUE THREAD

**Issue by MeetRajput00** [MeetRajput00/Socket-Wizard#6]
Instead of using the hard coded values for common ports, port services and os detection ports. Use the values from the files in temp_files instead.

**Comment by SahanY099** [comment]
Hey @MeetRajput00 I am new to open source. I saw this issue on a quick search. I would be verry happy to contribute this project. Can you give me a little guide?

**Comment by MeetRajput00** [comment]
Sure thing @SahanY099. I have added a Contributions.md file in this project, you can use this file as a reference to make contributions in this project. It's steps are generalized and you can use them to make contributions to any projects.
If you get stuck on any step, feel free to reach out.

**Comment by SahanY099** [comment]
Ok @MeetRajput00. I'll do my best to improve this project 😊.

**Comment by MeetRajput00** [comment]
Cool. Keep learning ✅

**Comment by SahanY099** [comment]
Hey, I noticed that in the os_detection_ports.txt uses just a raw dictionary like data format. How about using a json file to store those data?. There we can load that into the os_dict.

**Comment by MeetRajput00** [comment]
Hmm, good idea. Go for it.

**Comment by SahanY099** [comment]
👍 I am working on it.

**Comment by SahanY099** [comment]
Hey @MeetRajput00, I created a pull request for this issue. Can you please take a look that 😊.

**Comment by MeetRajput00** [comment]
Hi @SahanY099, great work with the pr. There are just some issues which I've commented out in your pr, can you please check them?

**Comment by SahanY099** [comment]
I'll look at it. Thanks for your attention 👍
